name: Openwrt-AutoBuild-Lean

on: 
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - main
    paths:
      - '.github/workflows/app.yml'
  #schedule:
  #  - cron: 0 2 * * *
  #watch:
  #  types: started

jobs:
  build:
    runs-on: Ubuntu-20.04
    
    name: Build luci-app-openclash
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64]
        
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: 解压下载好的 SDK
      run: |
        wget https://archive.openwrt.org/snapshots/trunk/x86/64/OpenWrt-SDK-x86-64_gcc-5.3.0_musl-1.1.16.Linux-x86_64.tar.bz2
        tar xjf OpenWrt-SDK-x86-64_gcc-5.3.0_musl-1.1.16.Linux-x86_64.tar.bz2
        cd OpenWrt-SDK-x86-64_gcc-5.3.0_musl-1.1.16.Linux-x86_64
        
    - name: Clone 项目
      run: |
        cd OpenWrt-SDK-x86-64_gcc-5.3.0_musl-1.1.16.Linux-x86_64
        mkdir package/luci-app-openclash
        cd package/luci-app-openclash
        git init
        git remote add -f origin https://github.com/vernesong/OpenClash.git
        git config core.sparsecheckout true
        echo "luci-app-openclash" >> .git/info/sparse-checkout
        git pull --depth 1 origin master
        git branch --set-upstream-to=origin/master master
    
    - name: 编译 po2lmo (如果有po2lmo可跳过)
      run: |
        cd OpenWrt-SDK-x86-64_gcc-5.3.0_musl-1.1.16.Linux-x86_64
        cd package/luci-app-openclash
        pushd luci-app-openclash/tools/po2lmo
        make && sudo make install
        popd

    - name: 开始编译
      run: | 
        cd ../..
        make package/luci-app-openclash/luci-app-openclash/compile V=99
